import React from 'react';
export const pricingDetails = () => <div>pricing distinct</div>;
export const pricing_detail_0 = (p:any)=> <div>pricing 0 weight</div>;
export const pricing_detail_1 = (p:any)=> <div>pricing 1 gem cost</div>;
export const pricing_detail_2 = (p:any)=> <div>pricing 2 labor</div>;
export const pricing_detail_3 = (p:any)=> <div>pricing 3 markup</div>;
export const pricing_detail_4 = (p:any)=> <div>pricing 4 weight</div>;
export const pricing_detail_5 = (p:any)=> <div>pricing 5 gem cost</div>;
export const pricing_detail_6 = (p:any)=> <div>pricing 6 labor</div>;
export const pricing_detail_7 = (p:any)=> <div>pricing 7 markup</div>;
export const pricing_detail_8 = (p:any)=> <div>pricing 8 weight</div>;
export const pricing_detail_9 = (p:any)=> <div>pricing 9 gem cost</div>;
export const pricing_detail_10 = (p:any)=> <div>pricing 10 labor</div>;
export const pricing_detail_11 = (p:any)=> <div>pricing 11 markup</div>;
export const pricing_detail_12 = (p:any)=> <div>pricing 12 weight</div>;
export const pricing_detail_13 = (p:any)=> <div>pricing 13 gem cost</div>;
export const pricing_detail_14 = (p:any)=> <div>pricing 14 labor</div>;
export const pricing_detail_15 = (p:any)=> <div>pricing 15 markup</div>;
export const pricing_detail_16 = (p:any)=> <div>pricing 16 weight</div>;
export const pricing_detail_17 = (p:any)=> <div>pricing 17 gem cost</div>;
export const pricing_detail_18 = (p:any)=> <div>pricing 18 labor</div>;
export const pricing_detail_19 = (p:any)=> <div>pricing 19 markup</div>;